- include_tasks: packages.yml
  tags: packages

- include_tasks: ntp.yml
  tags: ntp

- include_tasks: locale.yml
  tags: locale

- include_tasks: host.yml
  when: "hostname is defined"
  tags: host

- include_tasks: motd.yml
  tags: motd

